spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  main:
    banner-mode: OFF
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true
    username: root
    password: root

#  spring.main.banner-mode=off
#
#  spring.jpa.hibernate.ddl-auto=create-drop
#  spring.datasource.url=jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true
#  spring.datasource.username=root
#  spring.datasource.password=root
#  spring.jpa.show-sql = true
#  spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#  spring.jpa.properties.hibernate.format_sql=true
